name: Try Runtime

on:
  pull_request:
    branches: [main, devnet-ready, devnet, testnet, finney]
    types: [labeled, unlabeled, synchronize]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-devnet:
    name: check devnet
    runs-on: JungochainCI
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run Try Runtime Checks
        uses: "paritytech/try-runtime-gha@v0.1.0"
        with:
          runtime-package: "jungochain-runtime"
          node-uri: "wss://dev.chain.opentensor.ai:443"
          checks: "all"
          extra-args: "--disable-spec-version-check --no-weight-warnings"

  check-testnet:
    name: check testnet
    runs-on: JungochainCI
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run Try Runtime Checks
        uses: "paritytech/try-runtime-gha@v0.1.0"
        with:
          runtime-package: "jungochain-runtime"
          node-uri: "wss://test.chain.opentensor.ai:443"
          checks: "all"
          extra-args: "--disable-spec-version-check --no-weight-warnings"

  check-finney:
    name: check finney
    runs-on: JungochainCI
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Run Try Runtime Checks
        uses: "paritytech/try-runtime-gha@v0.1.0"
        with:
          runtime-package: "jungochain-runtime"
          node-uri: "wss://archive.chain.opentensor.ai:443"
          checks: "all"
          extra-args: "--disable-spec-version-check --no-weight-warnings"
